version: 2.1
description: "Example showing how to send a workflow metric events to CTO.ai. Set CTOAI_EVENTS_API_TOKEN and CTOAI_EVENTS_API_TEAM_ID env vars in CircleCI settings."

orbs:
  cto-ai: cto-ai/cto-ai@1.0.4
jobs:
  events_example_job:
    docker:
      - image: cimg/base:stable
    steps:
        - cto-ai/event:
            token: eeyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJSakpHbVhIUWhWdmZaOFJBUFNkZkhUNGJQUExOLThLNnNHOWFEclR1clM0In0.eyJqdGkiOiI4MjdkZmVlMy1jMzk2LTQ3ZDMtOGQxYi03MGM1ZjcyMGY1ZTMiLCJleHAiOjE2ODcwNDg4MjMsIm5iZiI6MCwiaWF0IjoxNjg0NDU2ODIzLCJpc3MiOiJodHRwczovL2N0by5haS9hdXRoL3JlYWxtcy9vcHMiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiNjQyNGFhZmYtZTBmZC00NDY1LWI0OWQtNWE4NDhiMzNjM2E5IiwidHlwIjoiQmVhcmVyIiwiYXpwIjoid3d3Iiwibm9uY2UiOiJhOWQ1ZTE0Yi0yZjRhLTQ1MWUtODA2Mi0wZjE0NmJlM2MzNTgiLCJhdXRoX3RpbWUiOjE2ODQyNTI4ODgsInNlc3Npb25fc3RhdGUiOiJlZTRmYTM5Ni1hNjY4LTRkODItYWM5OS0zY2M4ZDVhYmFjNDQiLCJhY3IiOiIwIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHA6Ly9sb2NhbGhvc3Q6ODA4MCIsImh0dHA6Ly9sb2NhbGhvc3Q6ODA4MSIsImh0dHA6Ly9sb2NhbGhvc3Q6MzAzMCJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIGVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibmFtZSI6Ik1hcmNvIEd1aWxsZW4iLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJtYXJjby5ndWlsbGVuIiwiZ2l2ZW5fbmFtZSI6Ik1hcmNvIiwiZmFtaWx5X25hbWUiOiJHdWlsbGVuIiwiZW1haWwiOiJtYXJjby5ndWlsbGVuQGN0by5haSJ9.iHruIe9M1ra4dpIQx3P2-m69m2iKIX_Ng2GlG7BxIw2AlnQIYeE5oA10FSUcUE6Zz54uwcK2G6dYNbKpdXrVjLWYIDilyC0DFucl6zV_mhCM9MyCODmMQurOtCRBSpFJwAkq7a-FJWp9bDqSfnBTbUXA3UjkK1srC1k0O1YHoa8u-YeK0g5daZ6mko6narc3RFYnR2dR1slb6fHkuKOIlDSABBSfaaw1M92VA1M-mFEfQBf2WOJX76v1ZBWPiGknuK47PUKDKxfIe8c3Vc8TB2cLaV4iiebM139H5wdM4X38oQbPbjhimT-3f6FEoy9BYeDuibtLqdlMb-2wJTB1iQ
            team_id: 6424aaff-e0fd-4465-b49d-5a848b33c3a9
            image: app78df3ba2
            environment: productions
            event_name: deployment
            event_action: succeeded
            repo: marcoguillenuio/prod-circleci-orb
            user: marcoguillenuio
workflows:
  events_example_workflow:
    jobs:
      - events_example_job