version: 2.1
description: "Example showing how to send a workflow metric events to CTO.ai. Set CTOAI_EVENTS_API_TOKEN and CTOAI_EVENTS_API_TEAM_ID env vars in CircleCI settings."

orbs:
  mgtracio-orb1: marcoguillenuio/mgtracio-orb1@dev:83931691c6bfeb15a30d7aa30f6aa65bcfbf9c68

jobs:
  events_example_job:
    docker:
      - image: cimg/base:stable
    steps:
        - mgtracio-orb1/event:
            token: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJoWWZ0T0FBN1Aycm9wemVHdlhCREZmQXptLThoS3lCTk5BcHZSSzBJYnhJIn0.eyJqdGkiOiI1OWNjZGRjMS02ZmI3LTQzYzEtOWNhMS03NzhlNWQ3NTIzMWYiLCJleHAiOjE2ODYyMjc2NjMsIm5iZiI6MCwiaWF0IjoxNjgzNjM1NjYzLCJpc3MiOiJodHRwczovL3d3dy5zdGctcGxhdGZvcm0uaGMuYWkvYXV0aC9yZWFsbXMvb3BzIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6ImQwMjhlMGQzLTg3NjEtNDQ5Ni05ZDBiLWNmMTgxZjNlYjZmYyIsInR5cCI6IkJlYXJlciIsImF6cCI6Ind3dyIsIm5vbmNlIjoiYWZiMDJhZDMtMjBmYS00NmJiLTlkYTMtMjA5ZmI5MzEwN2NkIiwiYXV0aF90aW1lIjoxNjgyMTE4MTA0LCJzZXNzaW9uX3N0YXRlIjoiMmYxZWMyNzItNDJjMC00M2Q2LTlmNGUtM2U0ZWZiZjEzOWM3IiwiYWNyIjoiMCIsImFsbG93ZWQtb3JpZ2lucyI6WyJodHRwczovL3d3dy5zdGctcGxhdGZvcm0uaGMuYWkiLCJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJodHRwOi8vMTI3LjAuMC4xOjgwODAiLCJodHRwOi8vbG9jYWxob3N0OjgwODEiLCJodHRwOi8vbG9jYWxob3N0OjMwMzAiLCJodHRwczovL3N0Zy12Mi5jdG8uYWkiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiJNYXJjbyBHdWlsbMOpbiIsInByZWZlcnJlZF91c2VybmFtZSI6Im1hcmNvLmd1aWxsZW4iLCJnaXZlbl9uYW1lIjoiTWFyY28iLCJmYW1pbHlfbmFtZSI6Ikd1aWxsw6luIiwiZW1haWwiOiJtYXJjby5ndWlsbGVuQGN0by5haSJ9.Cdnq4JsO-79RHV2zz96NuAPgTRQfG6vnxdSF9nicb9zH9qLFCskHZ07xd5caxZ1hWffniN66wGJAm_LLNUMSS9JIoMy1P9-uWitTJGLogm5D7hT8NHW9vLwPmmM_F65saH0SuamUhTK6SYQ8D1EI6DKpb8Fi-RcgxGnoPUcY9pg0UnS18iJ43_gN-BIwGOSfAQYjCu3OCjd0qo9wh-Oir9vN0ir9WAmK9O0DPwgW2tjaGTB174CoxDQB2y3qzpT3HyiMb4cxk_XvJ1kDp-djPVfLizbkIRIW1HC6BqVNCNma-D8-XLJa9_Kka7iQHkLHdKg4uW0cKpgLdx857Zfz5Q
            team_id: cd14278e-9c0c-4d95-9cc3-63ff0389a728
            image: app78df3bl8
            environment: staging
            event_name: deployment
            event_action: succeeded
            origin: circleci-orb
            vcs_type: gitlab
            branch: main
            repo: marcoguillenuio/marcoguillenuio
            user: marcoguillenuio
workflows:
  events_example_workflow:
    jobs:
      - events_example_job