version: 2.1
description: "Example showing how to send a workflow metric events to CTO.ai. Set CTOAI_EVENTS_API_TOKEN and CTOAI_EVENTS_API_TEAM_ID env vars in CircleCI settings."

orbs:
  mgtracio-orb1: marcoguillenuio/mgtracio-orb1@dev:83931691c6bfeb15a30d7aa30f6aa65bcfbf9c68

jobs:
  events_example_job:
    docker:
      - image: cimg/base:stable
    steps:
        - mgtracio-orb1/event:
            token: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJoWWZ0T0FBN1Aycm9wemVHdlhCREZmQXptLThoS3lCTk5BcHZSSzBJYnhJIn0.eyJqdGkiOiIyYjY1Y2RiNS1kODRhLTRkYTgtYTE1OS0xMTViZTg5MmUwN2EiLCJleHAiOjE2ODYyMzc2NjcsIm5iZiI6MCwiaWF0IjoxNjgzNjQ1NjY3LCJpc3MiOiJodHRwczovL3d3dy5zdGctcGxhdGZvcm0uaGMuYWkvYXV0aC9yZWFsbXMvb3BzIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6ImQwMjhlMGQzLTg3NjEtNDQ5Ni05ZDBiLWNmMTgxZjNlYjZmYyIsInR5cCI6IkJlYXJlciIsImF6cCI6Ind3dyIsIm5vbmNlIjoiNjBjODk2NDEtNDk3Yy00Yjg3LWFmZjMtYjRjY2E5ZTBiMGNmIiwiYXV0aF90aW1lIjoxNjgyMTE4MTA0LCJzZXNzaW9uX3N0YXRlIjoiMmYxZWMyNzItNDJjMC00M2Q2LTlmNGUtM2U0ZWZiZjEzOWM3IiwiYWNyIjoiMCIsImFsbG93ZWQtb3JpZ2lucyI6WyJodHRwczovL3d3dy5zdGctcGxhdGZvcm0uaGMuYWkiLCJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJodHRwOi8vMTI3LjAuMC4xOjgwODAiLCJodHRwOi8vbG9jYWxob3N0OjgwODEiLCJodHRwOi8vbG9jYWxob3N0OjMwMzAiLCJodHRwczovL3N0Zy12Mi5jdG8uYWkiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiJNYXJjbyBHdWlsbMOpbiIsInByZWZlcnJlZF91c2VybmFtZSI6Im1hcmNvLmd1aWxsZW4iLCJnaXZlbl9uYW1lIjoiTWFyY28iLCJmYW1pbHlfbmFtZSI6Ikd1aWxsw6luIiwiZW1haWwiOiJtYXJjby5ndWlsbGVuQGN0by5haSJ9.TI4XP8jiusOG99gAc82Jb6dJt-0qS7Y7lP3fpSaBcNkklNFDidjPiRtDAYvBPe30GhQ9ZNX83P5X0ryeqFDUCfcoTMnU5qJouCJQx87n1ptDS3Hd7LvA8kMRzBHCbOmw5wN49EPjWNVUBumPc8Mf_QCNi9TTTibfN7EPE0iIO0okM9Yv-4R8ZaB9icDDKrB8n21fHS4ahRhU9BMXZBRSiz2EnnUg6EbZIouHnlUlMluKUeoAQEgzsxbpkYzemUbbsNeTd34ylIQUyqNOUR4dhPpDq-gYbPcF5PKnR5u-qbTRlcP0KaKC7ZlzV1D2tho7TiPb9VPm668XqlDWszKq6g
            team_id: cd14278e-9c0c-4d95-9cc3-63ff0389a728
            image: app78df3bl11
            environment: staging
            event_name: deployment
            event_action: succeeded
            origin: circleci-orb
            vcs_type: github
            branch: main
            repo: marcoguillenuio/marcoguillenuio
            user: marcoguillenuio
workflows:
  events_example_workflow:
    jobs:
      - events_example_job