version: 2.1
description: "Example showing how to send a workflow metric events to CTO.ai. Set CTOAI_EVENTS_API_TOKEN and CTOAI_EVENTS_API_TEAM_ID env vars in CircleCI settings."

orbs:
  cto-ai: cto-ai/cto-ai@a8c3c65efd41bea4547a79d05bfde8b01fbebf08

jobs:
  orb_test:
    docker:
      - image: cimg/base:stable
    steps:
      - cto-ai/event:
          token: ${CTOAI_EVENTS_API_TOKEN}
          team_id: ${CTOAI_EVENTS_API_TEAM_ID}
          image: app78df3bl2
          environment: staging
          event_name: deployment
          event_action: succeeded
          origin: circleci-orb

workflows:
  orb_test_workflow:
    jobs:
      - orb_test