version: 2.1
description: "Example showing how to send a workflow metric events to CTO.ai. Set CTOAI_EVENTS_API_TOKEN and CTOAI_EVENTS_API_TEAM_ID env vars in CircleCI settings."

orbs:
  mgtracio-orb1: marcoguillenuio/mgtracio-orb1@dev:d0ccdf838ae60541c8ad59834762dc56a446fc0f

jobs:
  events_example_job:
    docker:
      - image: cimg/base:stable
    steps:
        - mgtracio-orb1/event:
            token: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJoWWZ0T0FBN1Aycm9wemVHdlhCREZmQXptLThoS3lCTk5BcHZSSzBJYnhJIn0.eyJqdGkiOiJhNDY3MTk3ZC0yNTJhLTQwMDgtYTFiNS1iMGM5MmNiYjhlYTQiLCJleHAiOjE2ODYxOTA2NzUsIm5iZiI6MCwiaWF0IjoxNjgzNTk4Njc1LCJpc3MiOiJodHRwczovL3d3dy5zdGctcGxhdGZvcm0uaGMuYWkvYXV0aC9yZWFsbXMvb3BzIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6ImQwMjhlMGQzLTg3NjEtNDQ5Ni05ZDBiLWNmMTgxZjNlYjZmYyIsInR5cCI6IkJlYXJlciIsImF6cCI6Ind3dyIsIm5vbmNlIjoiOTUzOTJiNjMtOGI2MS00ZGFhLTg5N2EtN2ViYmNlZDA2MDgyIiwiYXV0aF90aW1lIjoxNjgyMTE4MTA0LCJzZXNzaW9uX3N0YXRlIjoiMmYxZWMyNzItNDJjMC00M2Q2LTlmNGUtM2U0ZWZiZjEzOWM3IiwiYWNyIjoiMCIsImFsbG93ZWQtb3JpZ2lucyI6WyJodHRwczovL3d3dy5zdGctcGxhdGZvcm0uaGMuYWkiLCJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJodHRwOi8vMTI3LjAuMC4xOjgwODAiLCJodHRwOi8vbG9jYWxob3N0OjgwODEiLCJodHRwOi8vbG9jYWxob3N0OjMwMzAiLCJodHRwczovL3N0Zy12Mi5jdG8uYWkiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiJNYXJjbyBHdWlsbMOpbiIsInByZWZlcnJlZF91c2VybmFtZSI6Im1hcmNvLmd1aWxsZW4iLCJnaXZlbl9uYW1lIjoiTWFyY28iLCJmYW1pbHlfbmFtZSI6Ikd1aWxsw6luIiwiZW1haWwiOiJtYXJjby5ndWlsbGVuQGN0by5haSJ9.NkrU11b-hgS1dtGMInunxci_jLS3jqtzvHTp_4vfADRPqfdjDeyErPCrlKrNbVXTRj9Z0v42u9N_fSY9o5ipkasKqHaEKQWuUD7FTM9eC-e4SGCs_Mmw0FkihHpC-J0U-DG5kCl1uCZsOjcQGjHhQenWuBL7pJoOnzAMvu_38XF7fEME2hdabAIMGzDfVrlQAfx39fSHKQsFtrAI4BHGvSeBYMVZPGWlwMfZ32JxjGAipZyGadCqtD7GflhjIiG8MgEwjXr3X_zSEqDuqFqGh74OASXHCqOEaEJW0f2rQBKxYpp-yZbBGeXJO3OlxB6-CJOlpVZUsKnrsBLD4eJvtA
            team_id: cd14278e-9c0c-4d95-9cc3-63ff0389a728
            image: app78df3bl4
            environment: staging
            event_name: deployment
            event_action: succeeded
            origin: circleci-orb
workflows:
  events_example_workflow:
    jobs:
      - events_example_job