version: 2.1
description: "Example showing how to send a workflow metric events to CTO.ai. Set CTOAI_EVENTS_API_TOKEN and CTOAI_EVENTS_API_TEAM_ID env vars in CircleCI settings."

orbs:
  mgtracio-orb1: marcoguillenuio/mgtracio-orb1@dev:b08e40e8777c409ff3fda8e4419541be34a265cd

jobs:
  events_example_job:
    docker:
      - image: cimg/base:stable
    steps:
        - mgtracio-orb1/event:
            token: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJoWWZ0T0FBN1Aycm9wemVHdlhCREZmQXptLThoS3lCTk5BcHZSSzBJYnhJIn0.eyJqdGkiOiJiYTBlYzEzMi0zMjFmLTQyNGQtYmUxNS02OTI5NDhlZjA1MDciLCJleHAiOjE2ODYxOTI2ODIsIm5iZiI6MCwiaWF0IjoxNjgzNjAwNjgyLCJpc3MiOiJodHRwczovL3d3dy5zdGctcGxhdGZvcm0uaGMuYWkvYXV0aC9yZWFsbXMvb3BzIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6ImQwMjhlMGQzLTg3NjEtNDQ5Ni05ZDBiLWNmMTgxZjNlYjZmYyIsInR5cCI6IkJlYXJlciIsImF6cCI6Ind3dyIsIm5vbmNlIjoiMmM5NGI2ZTktZjE4Yy00Zjc5LWI4NGEtZThmMGRhZjNkOTU3IiwiYXV0aF90aW1lIjoxNjgyMTE4MTA0LCJzZXNzaW9uX3N0YXRlIjoiMmYxZWMyNzItNDJjMC00M2Q2LTlmNGUtM2U0ZWZiZjEzOWM3IiwiYWNyIjoiMCIsImFsbG93ZWQtb3JpZ2lucyI6WyJodHRwczovL3d3dy5zdGctcGxhdGZvcm0uaGMuYWkiLCJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJodHRwOi8vMTI3LjAuMC4xOjgwODAiLCJodHRwOi8vbG9jYWxob3N0OjgwODEiLCJodHRwOi8vbG9jYWxob3N0OjMwMzAiLCJodHRwczovL3N0Zy12Mi5jdG8uYWkiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiJNYXJjbyBHdWlsbMOpbiIsInByZWZlcnJlZF91c2VybmFtZSI6Im1hcmNvLmd1aWxsZW4iLCJnaXZlbl9uYW1lIjoiTWFyY28iLCJmYW1pbHlfbmFtZSI6Ikd1aWxsw6luIiwiZW1haWwiOiJtYXJjby5ndWlsbGVuQGN0by5haSJ9.gYYPeETY78uNEyiS2Oye1EOCmz6Nh8qgZXma06Zv7H7ovaxam1h5FNT8JfFkg5ZoPkvNgpQLwVypyNHZOwUwaz8WoRQ8c1-YaOY6p93ERWktMJw1D_Uzm5PAuA7rpXmBwsxIPhOsBbq0mpm5QmR2BlxbRskMPeeNW184fYzyMdXROHzss9xrxLeGUUTZn-OvgBFE2ZKI9tEhCTI4zVh_JgbSlhx9kYFTVMqavJpolQr09gTpvOY0TAxm6bKEB4jBdAEgYP8E_BhdGYwyW80LRrhe778aIHkd7TbAOx3op964ptkWfY0L6DLDc0i2AjEmk9HklWll8f1fZ_VIAR01iQ
            team_id: cd14278e-9c0c-4d95-9cc3-63ff0389a728
            image: app78df3bl6
            environment: staging
            event_name: deployment
            event_action: succeeded
            origin: circleci-orb
workflows:
  events_example_workflow:
    jobs:
      - events_example_job