version: 2.1
description: "Example showing how to send a workflow metric events to CTO.ai. Set CTOAI_EVENTS_API_TOKEN and CTOAI_EVENTS_API_TEAM_ID env vars in CircleCI settings."

orbs:
  mgtracio-orb1: marcoguillenuio/mgtracio-orb1@dev:b62ab9f2d0eba89afc7c22d02b74156bffc2b7db

jobs:
  events_example_job:
    docker:
      - image: cimg/base:stable
    steps:
        - mgtracio-orb1/event:
            token: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJoWWZ0T0FBN1Aycm9wemVHdlhCREZmQXptLThoS3lCTk5BcHZSSzBJYnhJIn0.eyJqdGkiOiI5ZjhmN2Q5Mi01NGM1LTQ2YmYtYjc5NS1iZTlkZDM1YjUxOGUiLCJleHAiOjE2ODYxOTEwNjgsIm5iZiI6MCwiaWF0IjoxNjgzNTk5MDY4LCJpc3MiOiJodHRwczovL3d3dy5zdGctcGxhdGZvcm0uaGMuYWkvYXV0aC9yZWFsbXMvb3BzIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6ImQwMjhlMGQzLTg3NjEtNDQ5Ni05ZDBiLWNmMTgxZjNlYjZmYyIsInR5cCI6IkJlYXJlciIsImF6cCI6Ind3dyIsIm5vbmNlIjoiMTVmNTIzMTItNjVhNi00ODdhLWI2ZWQtMTcwYTA4NTI4MjVlIiwiYXV0aF90aW1lIjoxNjgyMTE4MTA0LCJzZXNzaW9uX3N0YXRlIjoiMmYxZWMyNzItNDJjMC00M2Q2LTlmNGUtM2U0ZWZiZjEzOWM3IiwiYWNyIjoiMCIsImFsbG93ZWQtb3JpZ2lucyI6WyJodHRwczovL3d3dy5zdGctcGxhdGZvcm0uaGMuYWkiLCJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJodHRwOi8vMTI3LjAuMC4xOjgwODAiLCJodHRwOi8vbG9jYWxob3N0OjgwODEiLCJodHRwOi8vbG9jYWxob3N0OjMwMzAiLCJodHRwczovL3N0Zy12Mi5jdG8uYWkiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiJNYXJjbyBHdWlsbMOpbiIsInByZWZlcnJlZF91c2VybmFtZSI6Im1hcmNvLmd1aWxsZW4iLCJnaXZlbl9uYW1lIjoiTWFyY28iLCJmYW1pbHlfbmFtZSI6Ikd1aWxsw6luIiwiZW1haWwiOiJtYXJjby5ndWlsbGVuQGN0by5haSJ9.VXyd5Nd6bBL1gh5gIL8zvCTpGmPPv14YAW7AI6z02Czxqvdn3AQxzbtbYQtT8wR9JLWlU6BsFPNYSnhtq0-R1RvzOVIGZfHUvFWoiaI7k97sZC9HHDU-cC-QP-RH0jGdY_384yhXi61IoBV0VeDHIV5Vfrm69EXLdTGtBl4JsnY59k4CXPhuPP-YfwOyo9zqy4T2cpYDEgz7jInXvVEdy-yNND147tGI4mhkn0ka_1eh-a3iw1GFHWKI-YQIOfDWL09Lk7C3K30Dx5CA0RcX5ia34PUyte__5ax8IWfxJcrPErzR6I_zrdtFKqUxyZeUKqsFhScxef1LtMr8hoVWSw
            team_id: cd14278e-9c0c-4d95-9cc3-63ff0389a728
            image: app78df3bl5
            environment: staging
            event_name: deployment
            event_action: succeeded
            origin: circleci-orb
workflows:
  events_example_workflow:
    jobs:
      - events_example_job