version: 2.1
description: "Example showing how to send a workflow metric events to CTO.ai. Set CTOAI_EVENTS_API_TOKEN and CTOAI_EVENTS_API_TEAM_ID env vars in CircleCI settings."

orbs:
  mgtracio-orb1: marcoguillenuio/mgtracio-orb1@dev:d0ccdf838ae60541c8ad59834762dc56a446fc0f

jobs:
  events_example_job:
    docker:
      - image: cimg/base:stable
    steps:
        - mgtracio-orb1/event:
            token: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJoWWZ0T0FBN1Aycm9wemVHdlhCREZmQXptLThoS3lCTk5BcHZSSzBJYnhJIn0.eyJqdGkiOiI1MmY2NWU4My01YTA1LTQ0YTYtYjdkZi0zOTA2ZDRjZTg4ZWEiLCJleHAiOjE2ODYxODQ1MzQsIm5iZiI6MCwiaWF0IjoxNjgzNTkyNTM0LCJpc3MiOiJodHRwczovL3d3dy5zdGctcGxhdGZvcm0uaGMuYWkvYXV0aC9yZWFsbXMvb3BzIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6ImQwMjhlMGQzLTg3NjEtNDQ5Ni05ZDBiLWNmMTgxZjNlYjZmYyIsInR5cCI6IkJlYXJlciIsImF6cCI6Ind3dyIsIm5vbmNlIjoiNGZkM2FjODMtOTlkYi00MzhmLWEwNGUtNjQ5ZmQ0YjFlMWZkIiwiYXV0aF90aW1lIjoxNjgyMTE4MTA0LCJzZXNzaW9uX3N0YXRlIjoiMmYxZWMyNzItNDJjMC00M2Q2LTlmNGUtM2U0ZWZiZjEzOWM3IiwiYWNyIjoiMCIsImFsbG93ZWQtb3JpZ2lucyI6WyJodHRwczovL3d3dy5zdGctcGxhdGZvcm0uaGMuYWkiLCJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJodHRwOi8vMTI3LjAuMC4xOjgwODAiLCJodHRwOi8vbG9jYWxob3N0OjgwODEiLCJodHRwOi8vbG9jYWxob3N0OjMwMzAiLCJodHRwczovL3N0Zy12Mi5jdG8uYWkiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiJNYXJjbyBHdWlsbMOpbiIsInByZWZlcnJlZF91c2VybmFtZSI6Im1hcmNvLmd1aWxsZW4iLCJnaXZlbl9uYW1lIjoiTWFyY28iLCJmYW1pbHlfbmFtZSI6Ikd1aWxsw6luIiwiZW1haWwiOiJtYXJjby5ndWlsbGVuQGN0by5haSJ9.SqHz1iNcxnM5Vg8443Cwf4vW7nTBwMylf5B2GzTuqkU-onZuDavIEGi2lzoIdMjlnhFGdo78VZVSfJTGy20s4IwQh-Cy0PUpEk64SxXOcHlX88K4Z9e0AoWqZZDC46lwROueD00IwL8R_JaQMShFqWrtAUfTw-JG-IyGidQPOuELJgaqCQiLKsfpfhn6YwbLK63ST4NGxRttor9Fsi-H7BKj93RU-HybxpM17I0hzIFyhgxx3hNwD9fRCzPTS8WboJo5HeldDMl1bzphZcVspha3pwB1ONFegdeJzHMhM3hWLTmL6bB4dVKPURs48GWM9vHUVKvadZ3vrqdMw0F3Aw
            team_id: cd14278e-9c0c-4d95-9cc3-63ff0389a728
            image: app78df3bl4
            environment: staging
            event_name: deployment
            event_action: succeeded
            origin: circleci-orb
workflows:
  events_example_workflow:
    jobs:
      - events_example_job