version: 2.1
description: "Example showing how to send a workflow metric events to CTO.ai. Set CTOAI_EVENTS_API_TOKEN and CTOAI_EVENTS_API_TEAM_ID env vars in CircleCI settings."

orbs:
  cto-ai: cto-ai/cto-ai@1.0.4
jobs:
  events_example_job:
    docker:
      - image: cimg/base:stable
    steps:
        - cto-ai/event:
            token: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJSakpHbVhIUWhWdmZaOFJBUFNkZkhUNGJQUExOLThLNnNHOWFEclR1clM0In0.eyJqdGkiOiIxNmUyMmZiOC04NTczLTRkNTUtODg0ZC02ZWE4OTkxNzZjYTciLCJleHAiOjE2ODc2MzE5MTksIm5iZiI6MCwiaWF0IjoxNjg1MDM5OTE5LCJpc3MiOiJodHRwczovL2N0by5haS9hdXRoL3JlYWxtcy9vcHMiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiNjQyNGFhZmYtZTBmZC00NDY1LWI0OWQtNWE4NDhiMzNjM2E5IiwidHlwIjoiQmVhcmVyIiwiYXpwIjoid3d3Iiwibm9uY2UiOiJjMDcyMjUwMi1mNjMyLTRjYjMtOGM0ZC01MmVjMWY5YzJiZTQiLCJhdXRoX3RpbWUiOjE2ODQyNTI4ODgsInNlc3Npb25fc3RhdGUiOiJlZTRmYTM5Ni1hNjY4LTRkODItYWM5OS0zY2M4ZDVhYmFjNDQiLCJhY3IiOiIwIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHA6Ly9sb2NhbGhvc3Q6ODA4MCIsImh0dHA6Ly9sb2NhbGhvc3Q6ODA4MSIsImh0dHA6Ly9sb2NhbGhvc3Q6MzAzMCJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIGVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibmFtZSI6Ik1hcmNvIEd1aWxsZW4iLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJtYXJjby5ndWlsbGVuIiwiZ2l2ZW5fbmFtZSI6Ik1hcmNvIiwiZmFtaWx5X25hbWUiOiJHdWlsbGVuIiwiZW1haWwiOiJtYXJjby5ndWlsbGVuQGN0by5haSJ9.nJkfV962Ap4Au0a2wCDWN3g-Y7k0BdTjl9OPGzCm12aILue9P1UKRgsLt-2G-9-z6llXemHhvgJKWYc3AgPVmoYcvwp58HXC3JegcRraF9jPoVEbpYvie5xbrldI9du10uyLJ7tO2QNK7DzAmF9F41_3kntyJCcnAl9qMYNPdRWipLfiq3ELY0Z7-ITSwOGPMefGdzod3CkKl963PGvnlqzQm-RWPgaPArpE5SyWuJHDnwirEUxT1kHs3J2Iqf04IO0_tyjqKS0Sve3fdp_gqIZuTTZx1mocpy2cGhCzcwD4P0ZXwJ_09Iybyy92x8E0WeHIMDSBdPbGUaH5LsvowA
            team_id: 6424aaff-e0fd-4465-b49d-5a848b33c3a9
            image: app78df3ba2
            environment: production
            event_name: deployment
            event_action: succeeded
            repo: marcoguillenuio/circleci-architecture-events-deploy
            user: marcoguillenuio
workflows:
  events_example_workflow:
    jobs:
      - events_example_job