version: 2.1
description: "Example showing how to send a workflow metric events to CTO.ai. Set CTOAI_EVENTS_API_TOKEN and CTOAI_EVENTS_API_TEAM_ID env vars in CircleCI settings."

orbs:
  cto-ai: cto-ai/cto-ai@1.0.4
jobs:
  events_example_job:
    docker:
      - image: cimg/base:stable
    steps:
        - cto-ai/event:
            token: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJSakpHbVhIUWhWdmZaOFJBUFNkZkhUNGJQUExOLThLNnNHOWFEclR1clM0In0.eyJqdGkiOiIyYmQ1OTU4NC02YTBmLTQyMzQtYmRmMS05Yzc4YzA2MzhhYTEiLCJleHAiOjE2ODcwNDk5MDAsIm5iZiI6MCwiaWF0IjoxNjg0NDU3OTAwLCJpc3MiOiJodHRwczovL2N0by5haS9hdXRoL3JlYWxtcy9vcHMiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiNjQyNGFhZmYtZTBmZC00NDY1LWI0OWQtNWE4NDhiMzNjM2E5IiwidHlwIjoiQmVhcmVyIiwiYXpwIjoid3d3Iiwibm9uY2UiOiI3Y2I3NzljNi04ODlkLTQzZTktOWViYS1jZWNkNmY5ZGQ1YmQiLCJhdXRoX3RpbWUiOjE2ODQyNTI4ODgsInNlc3Npb25fc3RhdGUiOiJlZTRmYTM5Ni1hNjY4LTRkODItYWM5OS0zY2M4ZDVhYmFjNDQiLCJhY3IiOiIwIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHA6Ly9sb2NhbGhvc3Q6ODA4MCIsImh0dHA6Ly9sb2NhbGhvc3Q6ODA4MSIsImh0dHA6Ly9sb2NhbGhvc3Q6MzAzMCJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIGVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibmFtZSI6Ik1hcmNvIEd1aWxsZW4iLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJtYXJjby5ndWlsbGVuIiwiZ2l2ZW5fbmFtZSI6Ik1hcmNvIiwiZmFtaWx5X25hbWUiOiJHdWlsbGVuIiwiZW1haWwiOiJtYXJjby5ndWlsbGVuQGN0by5haSJ9.RK4J4CyzZsyteKaEb4UO_6U7Nf3saacb3jV8GudLU6jdUN-UvZtMx3MzmB3IBOatSJnsIeZLifXb9AWSErPRYrHTqQ4tIpgkrgvuDJmLbl-ZyYhcbt4f9oqBHgHqO90-A7Vhxxg-plUEl_EOYchfO-a9-xvLUtx7EKswKSCI4rYUgqwfgnKZh8asH_4WuYpI2S3zdPsdhiVZGe91snaLs519mUqmdg-M5H2AqFlFdifLaelxtU61US0Fi1vwwFvrZY0f-DJPDnNxo4zlDdeEfN4CJ3Nhl_QADKMog4vrxQnRP3INBVWQ7uI7Od2jKsNPiKrfbdwB_P_je1MrPi2dCg
            team_id: 6424aaff-e0fd-4465-b49d-5a848b33c3a9
            image: app78df3ba2
            environment: production
            event_name: deployment
            event_action: succeeded
            repo: marcoguillenuio/qa-prod-circleci-orb
            user: marcoguillenuio
workflows:
  events_example_workflow:
    jobs:
      - events_example_job