name: Github Job Deployment Success Test2
on:
  workflow_dispatch:
jobs:
  test-success:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci
      - name: 'Deployment Success2'
        run: |
          echo "Success Deployment"