name: Job Deployment Success - Single Step with Github Action
on:
  workflow_dispatch:
jobs:
  test-success:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'