name: Job Deployment Success - 2 Step2
on:
  workflow_dispatch:
jobs:
  test-success:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: 'Deployment Success - Single Step'
        run: |
          echo "Success Deployment"